version: "3.5"
services:
    crawler:
        image: fastapi-crawler
        build: .
        stdin_open: true
        tty: true
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_ROOT_USER=${MONGO_ROOT_USER}
            - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        volumes:
            - ./crawler/:/home/fastapi/crawler/
    fastapi:
        image: fastapi-crawler
        build: .
        stdin_open: true
        tty: true
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_ROOT_USER=${MONGO_ROOT_USER}
            - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        ports:
            - "8000:8000"
        volumes:
            - ./app/:/home/fastapi/app/
        command: python app/main.py
    mongo:
        image: mongo:5.0.11
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=project
        ports:
            - "27017:27017"
        volumes:
            - mongo-mount-data:/data/db
            - mongo-mount-data:/docker-entrypoint-initdb.d/
        restart: unless-stopped
        command: mongod
    mongo-express:
        image: mongo-express:1.0.0-alpha.4
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongo
        restart: unless-stopped
        ports:
            - "8081:8081"

volumes:
    mongo-mount-data: